sudo: required
services:
  - docker

before_install:
  - docker build -t frankyda111/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true frankyda111/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "cicd"
  env: "Cicd-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-073032805649"
  bucket_path: "cicd"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
