const TodoActionTypes = {
  FETCH_TODO_COLLECTIONS_START: "FETCH_TODO_COLLECTIONS_START",
  FETCH_TODO_COLLECTIONS_SUCCESS: "FETCH_TODO_COLLECTIONS_SUCCESS",
  FETCH_TODO_COLLECTIONS_FAILURE: "FETCH_TODO_COLLECTIONS_FAILURE",
  POPULATE_TODO_COLLECTIONS: "POPULATE_TODO_COLLECTIONS",
  CREATE_TODO_COLLECTION_START: "CREATE_TODO_COLLECTION_START",
  ADD_TODO_COLLECTION: "ADD_TODO_COLLECTION",
  IS_FETCHING_COLLECTIONS_TRUE: "IS_FETCHING_COLLECTIONS_TRUE",
  IS_FETCHING_COLLECTIONS_FALSE: "IS_FETCHING_COLLECTIONS_FALSE",
  IS_FETCHING_TODO_ITEMS_TRUE: "IS_FETCHING_TODO_ITEMS_TRUE",
  IS_FETCHING_TODO_ITEMS_FALSE: "IS_FETCHING_TODO_ITEMS_FALSE",
  FETCH_TODO_ITEMS_FOR_A_COLLECTION_START: "FETCH_TODO_ITEMS_FOR_A_COLLECTION_START",
  FETCH_TODO_ITEMS_FOR_A_COLLECTION_SUCCESS: "FETCH_TODO_ITEMS_FOR_A_COLLECTION_SUCCESS",
  FETCH_TODO_ITEMS_FOR_A_COLLECTION_FAILURE: "FETCH_TODO_ITEMS_FOR_A_COLLECTION_FAILURE",
  POPULATE_TODO_ITEMS_TO_A_COLLECTION: "POPULATE_TODO_ITEMS_TO_A_COLLECTION",
  SET_OPENED_TODO_COLLECTION: "SET_OPENED_TODO_COLLECTION",
  TOGGLE_SIDEBAR_OPEN: "TOGGLE_SIDEBAR_OPEN",
  OPEN_TODO_SIDEBAR: "OPEN_TODO_SIDEBAR",
  CLOSE_TODO_SIDEBAR: "CLOSE_TODO_SIDEBAR",
  SET_TODO_SEARCH_TERM: "SET_TODO_SEARCH_TERM",
}

export default TodoActionTypes;