const GalleryActionTypes = {
    FETCH_PHOTOS_START: "FETCH_PHOTOS_START",
    FETCH_PHOTOS_SUCCESS: "FETCH_PHOTOS_SUCCESS",
    FETCH_PHOTOS_FAILURE: "FETCH_PHOTOS_FAILURE",
    POPULATE_MORE_GALLERY_PHOTOS: "POPULATE_MORE_GALLERY_PHOTOS",
    POPULATE_GALLERY_PHOTOS: "POPULATE_GALLERY_PHOTOS",
    SET_FETCHING_GALLERY_IMAGES_TRUE: "SET_FETCHING_GALLERY_IMAGES_TRUE",
    SET_FETCHING_GALLERY_IMAGES_FALSE: "SET_FETCHING_GALLERY_IMAGES_FALSE",
}

export default GalleryActionTypes;