const ThemeActionTypes = {
    SET_BACKGROUND_LUM: "SET_BACKGROUND_LUM",
    SET_USER_BACKGROUND: "SET_USER_BACKGROUND",
    SET_THEME: "SET_THEME",
    SET_THEME_START: "SET_THEME_START",
}

export default ThemeActionTypes;