const GeneralActionTypes = {
  TOGGLE_TODO_POPUP_OPEN: "TOGGLE_TODO_POPUP_OPEN",
  SET_RENDER_TODO_POPUP: "SET_RENDER_TODO_POPUP",
  SET_TODO_CONTEXT_MENU_TGT: "SET_TODO_CONTEXT_MENU_TGT",
}

export default GeneralActionTypes;