const UserActionTypes = {
    IS_UPLOADING_AVATAR_TRUE: "IS_UPLOADING_AVATAR_TRUE",
    IS_UPLOADING_AVATAR_FALSE: "IS_UPLOADING_AVATAR_FALSE",
    IS_UPDATING_USER_DETAILS_TRUE: "IS_UPDATING_USER_DETAILS_TRUE",
    IS_UPDATING_USER_DETAILS_FALSE: "IS_UPDATING_USER_DETAILS_FALSE",
    IS_CHANGING_USER_PASSWORD_TRUE: "IS_CHANGING_USER_PASSWORD_TRUE",
    IS_CHANGING_USER_PASSWORD_FALSE: "IS_CHANGING_USER_PASSWORD_FALSE",
    IS_DELETE_ME_TRUE: "IS_DELETE_ME_TRUE",
    IS_DELETE_ME_FALSE: "IS_DELETE_ME_FALSE",
    UPDATE_USER_DETAILS_START: "UPDATE_USER_DETAILS_START",
    UPDATE_USER_DETAILS_SUCCESS: "UPDATE_USER_DETAILS_SUCCESS",
    UPDATE_USER_DETAILS_FAILURE: "UPDATE_USER_DETAILS_FAILURE",
    UPDATE_USER_AVATAR_START: "UPDATE_USER_AVATAR_START",
    UPDATE_USER_AVATAR_SUCCESS: "UPDATE_USER_AVATAR_SUCCESS",
    UPDATE_USER_AVATAR_FAILURE: "UPDATE_USER_AVATAR_FAILURE",
    CHANGE_USER_PASSWORD_START: "CHANGE_USER_PASSWORD_START",
    CHANGE_USER_PASSWORD_SUCCESS: "CHANGE_USER_PASSWORD_SUCCESS",
    CHANGE_USER_PASSWORD_FAILURE: "CHANGE_USER_PASSWORD_FAILURE",
    DELETE_ME_START: "DELETE_ME_START",
    DELETE_ME_SUCCESS: "DELETE_ME_SUCCESS",
    DELETE_ME_FAILURE: "DELETE_ME_FAILURE",
}

export default UserActionTypes;